---
name: POE-Component-WWW-LimerickDB
version: 0.0103
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: non-blocking wrapper around WWW::LimerickDB
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE: 0.9999
  POE::Component::NonBlockingWrapper::Base: 0.002
  WWW::LimerickDB: 0.0304
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::LimerickDB:
    file: lib/POE/Component/WWW/LimerickDB.pm
    version: 0.0103
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
